# Generated by Django 4.2 on 2026-03-02 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Mywork', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workdetail',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='workdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
