# Generated by Django 4.2 on 2026-03-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mywork', '0002_alter_workdetail_options_workdetail_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workdetail',
            options={'ordering': ['-date', '-created_at']},
        ),
    ]
